name: Test
on:
- push
- pull_request
jobs:
  Test:
    name: Test nn4dms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: nn4dms
          environment-file: environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      # Log conda environment contents
      - name: Log conda environment
        shell: bash --login {0}
        run: conda list
      # Tests that the regression training code runs in the conda environment
      - name: Train regression example
        shell: bash --login {0}
        run: python code/regression.py @regression_args/example.txt
      # Tests that inference notebook can execute in the conda environment
      - name: Execute inference notebook
        shell: bash --login {0}
        run: jupyter-nbconvert --to html --inplace --execute notebooks/inference.ipynb --ExecutePreprocessor.timeout=-1
